### PR TITLE
Updated vite and vavite/multibuild versions to support vite 6

### LINKED ISSUE #18: Update vite version to `6.0.0`
### Package version

3.0.0

### Describe the bug

[Vite 6](https://vite.dev/blog/announcing-vite6) has recently released, and it would be nice for this plugin to support it as well.

I created this issue because I found out that this package using an older version of Vite has already caused problems when trying to use inertia with Vite and some kind of FE frameworks that already use `6.0.0` and it's new features like default values for `resolve.conditions` (https://vite.dev/guide/migration#default-value-for-resolve-conditions). 

Issue stemming from old version of Vite: https://github.com/adonisjs/inertia-starter-kit/issues/5

I can create a PR for this. I think only the versions of `vite` and `@vavite/multibuild` have to be updated.

### Reproduction repo

_No response_

### PR DESCRIPTION
**Pull request by Barabasbalazs**
### ❓ Type of change

- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Updated `vite` and `@vavite/multibuild` versions in order to avoid future incompatibility issues stemming from this.
Should also be applied in [inertia](https://github.com/adonisjs/inertia) repo.
Resolves #18.
### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by RomainLanz** [comment]
Hey @Barabasbalazs! 👋🏻 

Thank you for your PR! 🙌

Before we can merge it, we need to verify compatibility with Vite to ensure nothing breaks. If any issues arise, we'll need to schedule this update for a future major release.

**Comment by thetutlage** [comment]
@Julien-R44 Would like you to review this PR and Vite 6 support in general?

**Comment by Julien-R44** [comment]
Yup, as said here : https://github.com/adonisjs/vite/issues/18#issuecomment-2509787634

I'd like to see if we can improve SSR support via the new Environnement API proposed by Vite 6 before major bump. Gonna check that soon

**Comment by thetutlage** [comment]
@Julien-R44 

> I'd like to see if we can improve SSR support via the new Environnement API proposed by Vite 6 before major bump. Gonna check that soon

👀 Any ideas or plans in mind for this? Would love to know that :)

**Comment by Julien-R44** [comment]
Actually, we should probably be able to remove the usage of `@vavite/multibuild` thanks to the new Environment API, which allows for different builds per environment: https://vite.dev/guide/api-environment#custom-environment-instances. In our case, we’re mainly interested in SSR builds for Inertia

I’m not sure I fully understand everything yet, so yeah, I need to look into it more closely. also worth noting that Vite's Environment API is still experimental, so if we add support on our end, it would probably be opt-in and not used by default until it's stabilized

**Comment by Barabasbalazs** [comment]
Changing the `@vavite/multibuild` dependency doesn't look so complicated for this repo since it's only used to expose a build hook that launches the vite multi build process:

```TypeScript

import { multibuild } from '@vavite/multibuild'
import type { AssemblerHookHandler } from '@adonisjs/core/types/app'

/**
 * This is an Assembler hook that should be executed when the application is
 * builded using the `node ace build` command.
 *
 * The hook is responsible for launching a Vite multi-build process.
 */
export default async function viteBuildHook({ logger }: Parameters<AssemblerHookHandler>[0]) {
  logger.info('building assets with vite')

  await multibuild(undefined, {
    onStartBuildStep: (step) => {
      if (!step.currentStep.description) return

      logger.info(step.currentStep.description)
    },
  })
}

```
And Inertia only imports the types from this package right?

`vavite` already supports Vite 6 and as @Julien-R44 mentioned the `Environment API` is bound to change a lot once Vite 7 releases, since they're still collecting input from devs on how to best optimize it.

**Comment by Julien-R44** [comment]
Okay yeah, let's merge it, and see how we can use the Environment API later

Thanks for the PR!

**Comment by Julien-R44** [comment]
Finally, we can't. Check the `typecheck `job result. We are using the runtime API that was removed : https://vite.dev/guide/migration#vite-runtime-api

So we'll have to go back to `ssrLoadModule` or use the new Environment API now. I'll take care of it soon.

**Comment by Barabasbalazs** [comment]
So the typechecker cleared 2 things:
 
 1. That `ts-morph` also has to be updated.
 
 2. And that the `createViteRuntime` related functions are deprecated with the new Environment API.
 Before when creating a new Runtime for Inertia we had this small function where some options could be configured as well but from what I saw from the Inertia package they weren't really used:
 
 ```TypeScript
  async createRuntime(options: MainThreadRuntimeOptions = {}): Promise<ViteRuntime> {
    const { createViteRuntime } = await import('vite')

    return createViteRuntime(this.#devServer!, options)
  }
 ```
 With the new Environment API, this function should look something like this:
 ```TypeScript
 async createRuntime(
    options: ModuleRunnerOptions = {
      root: 'root',
      transport: undefined as unknown as ModuleRunnerTransport,
    }
  ): Promise<ModuleRunner> {
    const moduleRunner = new ModuleRunner(options, new ESModulesEvaluator())

    return moduleRunner.import('vite')
  }
  ```
  
 From what I saw, Vite now requires some hands on configuration when creating a new `ModuleRunner` (the replacement for `ViteRuntime`), and I'm not really sure what those would be for Ineria, so I just added some dummy values here in the example.
The docs are pretty extensive and maybe somebody has any ideas wich config would be best: https://vite.dev/guide/api-environment-runtimes.html
I'm updating the PR with these small changes so you guys can have a look and maybe discuss how to tackle these new `ModuleRunnerOptions`.

**Comment by Barabasbalazs** [comment]
After digging around the `Vite` docs and Github I was able to update PR so it uses the new API's exposed by Vite.

The main change has been that I rewrote the `createRuntime` function to this:

```TypeScript
 async createModuleRunner(options: ServerModuleRunnerOptions = {}): Promise<ModuleRunner> {
    const { createServerModuleRunner } = await import('vite')
    return createServerModuleRunner(this.#devServer!.environments.ssr, options)
  }
```

Inertia uses this to render pages on the Server in the `ServerRenderer` class, so in order to maximize effectiveness, the `vite` dependency would have to be updated there as well. This would be a breaking change for Inertia since the API types have changed, but I'd like to look into updating `vite` there as well.

@Julien-R44 please have a look at the PR, I made sure all the checks pass now.

**Comment by Julien-R44** [comment]
Thanks for taking care of this, dude! Will merge and take it from there. Thanks

**Pull request merged**
